#!/usr/bin/env python3
"""Generate STRATEGY_INDEX.md straight from the registry and the last run.

  python scripts/strategy_index.py
  python scripts/strategy_index.py --out STRATEGY_INDEX.md

Why this exists: a hand-written list of strategies drifts. This reads
`protocol.strategies.REGISTRY`, the configured parameters and the most recent
`reports/comparison.csv`, so "what strategies are there?" always has exactly
one authoritative answer.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from protocol.config import load_config  # noqa: E402
from protocol.strategies import REGISTRY  # noqa: E402

FAMILY = {
    "strategies": ("AAE core", "protocol/strategies.py"),
    "strategies_rank": ("cross-sectional rank", "protocol/strategies_rank.py"),
    "strategies_pra": ("PRA events", "protocol/strategies_pra.py"),
    "strategies_pa": ("Price-Acceptance + community", "protocol/strategies_pa.py"),
}


def load_results(path: Path) -> dict[str, dict[str, str]]:
    if not path.exists():
        return {}
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines:
        return {}
    head = lines[0].split(",")
    out: dict[str, dict[str, str]] = {}
    for line in lines[1:]:
        cells = line.split(",")
        if len(cells) != len(head):
            continue
        row = dict(zip(head, cells))
        out[row.get("Strategy", "")] = row
    return out


def build(cfg: dict, results: dict[str, dict[str, str]]) -> str:
    params = cfg.get("strategies") or {}
    families: dict[str, list[str]] = {}
    for name, fn in sorted(REGISTRY.items()):
        mod = (getattr(fn, "__module__", "") or "").split(".")[-1]
        families.setdefault(FAMILY.get(mod, ("other", mod))[0], []).append(name)

    L = ["# Strategy index (generated from the code)", "",
         "Do not hand-edit this file - it is regenerated by "
         "`python scripts/strategy_index.py`.", "",
         f"**{len(REGISTRY)} strategies registered.** "
         f"Rule-by-rule explanations live in [`STRATEGIES.md`](STRATEGIES.md); "
         "how to add one is in its final section.", "",
         "## How to read the columns", "",
         "| Column | Meaning |", "|---|---|",
         "| N | Completed trades in the most recent full-universe run |",
         "| Expectancy | Average **net** return per trade, all costs included |",
         "| 95% CI | Seeded bootstrap interval on that expectancy |",
         "| WinRate | Share of trades that reached the +15% target |",
         "| SafeRate | Share of trades that did **not** hit the stop |",
         "| TailBreach | Share of trades that lost more than -7% |",
         "",
         "`random` is the null: anything at or below it is noise.", ""]

    for family in sorted(families):
        L += [f"## {family}", "",
              "| # | Strategy | Params | N | Expectancy | WinRate | SafeRate | TailBreach |",
              "|---|---|---|---|---|---|---|---|"]
        for i, name in enumerate(families[family], 1):
            p = params.get(name) or {}
            pstr = ", ".join(f"`{k}={v}`" for k, v in p.items()) or "—"
            r = results.get(name, {})
            L.append(f"| {i} | `{name}` | {pstr} | {r.get('N', '—')} | "
                     f"{r.get('Expectancy', '—')} | {r.get('WinRate', '—')} | "
                     f"{r.get('SafeRate', '—')} | {r.get('TailBreach', '—')} |")
        L.append("")

    L += ["## Running a subset", "", "```bash",
          "python scripts/run_backtest.py --strategies all",
          "python scripts/run_backtest.py --strategies recovered_after_rej,random,trap",
          "python scripts/run_backtest.py --strategies aae_acceptance \\",
          "  --set state0.rvol_min=2.5 --set strategies.trap.ret2_min=0.20",
          "```", "",
          "Comparisons are only meaningful against `random` (the seeded null) and "
          "`cash` (the do-nothing baseline). `trap` is the fear the protocol was "
          "built to test - it is expected to lose.", ""]
    return "\n".join(L)


def main() -> int:
    ap = argparse.ArgumentParser(description="Generate the strategy index")
    ap.add_argument("--config", default=None)
    ap.add_argument("--results", default=str(ROOT / "reports" / "comparison.csv"))
    ap.add_argument("--out", default=str(ROOT / "STRATEGY_INDEX.md"))
    args = ap.parse_args()
    cfg = load_config(args.config)
    text = build(cfg, load_results(Path(args.results)))
    Path(args.out).write_text(text, encoding="utf-8")
    print(f"{len(REGISTRY)} strategies -> {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())